update deprecated api version
kubevirt/ovs-cni pull request #141
Opened 2020-11-17 14:50 UTC by pperiyasamy

This updates ClusterRole/ClusterRoleBinding kind apiVersion into `v1 `because `v1beta1 `
is already deprecated in K8s 1.17 and deployment of [ovs-cni.yml](https://github.com/kubevirt/ovs-cni/blob/master/examples/ovs-cni.yml) throws below warning.

```
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
```

Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

2020-11-17 14:51 UTC, pperiyasamy commented
/release-note-none

2020-11-25 16:13 UTC, phoracek requested changes
These files are generated based on https://github.com/kubevirt/ovs-cni/blob/master/manifests/ovs-cni.yml.in#L81. Would you please update the source and run `make manifests`?

2020-11-26 09:40 UTC, pperiyasamy commented
> These files are generated based on https://github.com/kubevirt/ovs-cni/blob/master/manifests/ovs-cni.yml.in#L81. Would you please update the source and run `make manifests`?

ah! yes, now updated the source file as well.

2020-11-26 09:42 UTC, pperiyasamy commented
/cc @JanScheurich

2020-11-26 14:21 UTC, phoracek commented
Thanks!

/lgtm
/approve

2020-11-26 14:22 UTC, merged